### ISSUE TITLE
Feature suggestion: make path to squint-cljs/core.js configurable 

### ISSUE THREAD

**Issue by mjmeintjes** [squint-cljs/squint#224]
It would be useful to be able to import squint-cljs/core.js from a cdn for example, or from a relative local path. This would allow using squint scripts in the browser without requiring bundling.

Import maps is a current solution, but not widely supported yet.

**Comment by borkdude** [comment]
I am using a ponyfill for import-maps though in that HTML.

**Comment by mjmeintjes** [comment]
I was having problems with import maps in Firefox, but didn't think of using a polyfill library. In that case this is probably not necessary.

**Comment by onetom** [comment]
1st time I heard about import maps, so it might worth mentioning a working example, like:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Squint lab</title>
  <script type="importmap">
      {
        "imports": {
          "squint-cljs": "./node_modules/squint-cljs",
          "squint-cljs/core.js": "./node_modules/squint-cljs/core.js"
        }
      }
  </script>
</head>
<body>

<h1>Squint lab</h1>
<script type="module">
  import * as example from './example.mjs'
</script>
</body>
</html>
```

where `example.mjs` is just
```clojure
(println "Hello from Squint!")
```

and it's compiled with `bunx squint compile example.cljs`, served with [`devd -l .`](https://github.com/cortesi/devd)

**Comment by borkdude** [comment]
Thanks for adding the extra info!
