### ISSUE TITLE
Alternative syntax for async function

### ISSUE THREAD

**Issue by mjmeintjes** [squint-cljs/squint#230]
I'm embedding squint code inside clojure functions as a quoted list, and then using squint.compiler/compile-string to convert the code to Javascript code. 

This works great, except for async functions, because the Clojure reader reads the metadata before it gets to the squint compiler.

For example, this works:
`(sq/compile-string "(defn ^:async afn [] 1)")` ==> `"var afn = async function () {\nreturn 1;\n}\n;\n\nexport { afn }\n"`
But this does not:
`(sq/compile-string (str '(defn ^:async afn [] 1))` ==> `"var afn = function () {\nreturn 1;\n}\n;\n\nexport { afn }\n" `

I was wondering if it is possible to have alternative syntax for specifying an async function (maybe just something like defn-async).

I know this is probably a niche use-case, so feel free to ignore.

**Comment by borkdude** [comment]
@mjmeintjes You can use `(binding [*print-meta* true] ...)` here:

``` clojure
user=> (binding [*print-meta* true] (str ^:async []))
"^{:async true} []"
```

**Comment by mjmeintjes** [comment]
Great, that works. Thanks!
