### ISSUE TITLE
_PLUS_ isn't required in compiled mjs file when used as an argument to functions like reduce or apply

### ISSUE THREAD

**Issue by armincerf** [squint-cljs/squint#244]
I'm guessing there are other cases where this happens, but so far here are my tests:

This cljs:
```
(println (apply inc [1 2 3]))
```

produces the expected js
```
import { println, apply, inc } from 'squint-cljs/core.js'
println(apply(inc, [1, 2, 3]));
```

however when using `+` it doesn't compile because the mjs file doesn't import `_PLUS_`
```
(println (apply + [1 2 3]))
```
produces
```
import { println, apply } from 'squint-cljs/core.js'
println(apply(_PLUS_, [1, 2, 3]));
```

And same when reduce is used instead of apply

**Comment by borkdude** [comment]
Will fix. This has to do with a bug in shadow-cljs and upgrading shadow-cljs will likely fix this.

**Comment by borkdude** [comment]
You can likely work around this by doing: `(reduce (fn [x y] (+ x y)) [1 2 3])` for now.

**Comment by borkdude** [comment]
Can you try version `0.0.1`?

**Comment by armincerf** [comment]
> Can you try version `0.0.1`?

Working nicely, thanks for the super quick response!

**Comment by borkdude** [comment]
@armincerf No problem. Keep the issues coming :)
