### ISSUE TITLE
Core-fn: keyword?

### ISSUE THREAD

**Issue by armincerf** [squint-cljs/squint#249]
I think this one is a bit tricky at the moment since `:foo` simply gets compiled to "foo" and there's no way to tell it came from a keyword. One possibility is to make it compile to `":foo"` but not sure what the implications of that are

**Comment by borkdude** [comment]
Compiling to `:foo` would not be a good choice imo since you then get a conflict with how the rest of the JS ecosystem works. Keywords are compiled to normal strings exactly because of interoperability with the JS ecosystem. I think it's better to avoid `keyword?` in squint for this reason.

**Comment by armincerf** [comment]
Yep makes sense, happy to close this
