### ISSUE TITLE
`source-maps` dev dependency fails to install on MS-Windows

### ISSUE THREAD

**Issue by ikappaki** [squint-cljs/squint#278]
Hi,

there appears to be an issue when npm tries to install the squint's package.json `source-maps` dev dependency on MS-Windows:

```
SourceMap.obj : error LNK2001: unresolved external symbol "struct std::atomic<bool> Napi::details::needs_objectwrap_destructor_fix" (?needs_objectwrap_destructor_fix@details@Napi@@3U?$atomic@_N@std@@A) [c:\ \removeme\package\build\sourcemap.vcxproj]
```

`source-maps` is a native node module that is build on the user's machine using a native compiler.

This is not a squint issue, since I can reproduce this outside of it. 

Given I couldn't find a public `source-maps` repository to raise this to, I've reported the issue to @jasperdm by email and raised this ticket for awareness. 

Excerpt from the email (edited for brevity)

> I’m using node 19.3.0 with VS2022 to compile the project.
>  
> The way to reproduce this on MS-Windows is to 
>  
> 1.	Install node.js 19.3
> 2.	Install Visual Studio community edition Desktop C++ package
> 3.	Install Python 3.10 from Microsoft store.
> 4.	`wget https://registry.npmjs.org/source-maps/-/source-maps-1.0.12.tgz` and unpack
> 5.	`cd package`
> 6.	`npm install`, and you should get the above error (full output at the end)
>  
>  
> I’m not familiar with node-addon-api  but the error goes away if I change the `node-addon-api` version to “^3.0.0” in package.json, suggesting there is a dependency version mismatch somewhere?
>  
> Error output:
>  
> $ npm install
>  
> > source-maps@1.0.12 install
> > node-gyp rebuild
>  
> gyp info it worked if it ends with ok
> gyp info using node-gyp@9.3.0
> gyp info using node@19.3.0 | win32 | x64
> gyp info find Python using Python version 3.10.9 found at "C:\Users\xyz\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
> gyp info find VS using VS2022 (17.4.33205.214) found at:
> gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
> gyp info find VS run with --verbose for detailed information
> gyp info spawn C:\Users\xyz\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe
> gyp info spawn args [
> gyp info spawn args   'c:\\Users\\xyz\\AppData\\Roaming\\nvm\\v19.3.0\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'msvs',
> gyp info spawn args   '-I',
> gyp info spawn args   'c:\\clj\\removeme\\package\\build\\config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   'c:\\Users\\xyz\\AppData\\Roaming\\nvm\\v19.3.0\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   'C:\\Users\\xyz\\AppData\\Local\\node-gyp\\Cache\\19.3.0\\include\\node\\common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=C:\\Users\\xyz\\AppData\\Local\\node-gyp\\Cache\\19.3.0',
> gyp info spawn args   '-Dnode_gyp_dir=c:\\Users\\xyz\\AppData\\Roaming\\nvm\\v19.3.0\\node_modules\\npm\\node_modules\\node-gyp',
> gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\xyz\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\19.3.0\\\\<(target_arch)\\\\node.lib',
> gyp info spawn args   '-Dmodule_root_dir=c:\\clj\\removeme\\package',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'c:\\clj\\removeme\\package\\build',
> gyp info spawn args   '-Goutput_dir=.'
> gyp info spawn args ]
> gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
> gyp info spawn args [
> gyp info spawn args   'build/binding.sln',
> gyp info spawn args   '/clp:Verbosity=minimal',
> gyp info spawn args   '/nologo',
> gyp info spawn args   '/p:Configuration=Release;Platform=x64'
> gyp info spawn args ]
> Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
>   nothing.c
>   win_delay_load_hook.cc
>   nothing.vcxproj -> c:\clj\removeme\package\build\Release\\nothing.lib
>   SourceMap.cpp
>   MappingContainer.cpp
>   MappingLine.cpp
>   Mapping.cpp
>   win_delay_load_hook.cc
>      Creating library c:\clj\removeme\package\build\Release\sourcemap.lib and object c:\clj\removeme\package\build\Release\sourcemap.exp
> SourceMap.obj : error LNK2001: unresolved external symbol "struct std::atomic<bool> Napi::details::needs_objectwrap_destructor_fix" (?needs_objectwrap_destructor_fix@details@Napi@@3U?$atomic@_N@std@@A) [c:\clj\removeme\package\build\sourcemap.vcxproj]
> c:\clj\removeme\package\build\Release\sourcemap.node : fatal error LNK1120: 1 unresolved externals [c:\clj\removeme\package\build\sourcemap.vcxproj]
> gyp ERR! build error 
> gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (c:\Users\xyz\AppData\Roaming\nvm\v19.3.0\node_modules\npm\node_modules\node-gyp\lib\build.js:203:23)
> gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
> gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
> gyp ERR! System Windows_NT 10.0.22621
> gyp ERR! command "d:\\Program Files\\nodejs\\node.exe" "c:\\Users\\xyz\\AppData\\Roaming\\nvm\\v19.3.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd c:\clj\removeme\package
> gyp ERR! node -v v19.3.0
> gyp ERR! node-gyp -v v9.3.0
> gyp ERR! not ok 
> npm ERR! code 1
> npm ERR! path c:\clj\removeme\package
> npm ERR! command failed
> npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
>  
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\xyz\AppData\Local\npm-cache\_logs\2022-12-30T15_16_05_538Z-debug-0.log
>

**Comment by ikappaki** [comment]
It turns out that the `source-maps` library is deprecated in favor of https://www.npmjs.com/package/@parcel/source-map

(as per @jasperdm)
> [...] you’re linking to the old source-maps library, that one has been deprecated in favour of the new one I linked in my last email, the new package is @parcel/source-map and should work on all windows platforms.

@borkdude, since this is now clarified and the package reference was provisionally removed with https://github.com/squint-cljs/compiler-common/pull/19 as unused, is there something more that needs to be done here (i.e. include `@parcel/source-map` as  a dev dependency replacement, even if it is not used) or can this issue be closed?

Thanks

**Comment by borkdude** [comment]
It's good to know that there is a replacement and we will use it when necessary, thank you.
