### ISSUE TITLE
Add option to configure compile file's extension

### ISSUE THREAD

**Issue by MTrost** [squint-cljs/squint#283]
Some JavaScript libraries and tools can't handle `.mjs` files (e.g. Remix, Photoshop were mentioned in Slack).

It would be great to have a way to tell squint what file extension it uses to create files with non-standard extensions possible (Photoshop uses `.psjs`).

Files containing `#jsx` should probably be constrained to `.jsx` (and `.tsx`?).

**Comment by borkdude** [comment]
Files containing #jsx are emitted as `.jsx` already automatically. If not, please provide a repro.
The extension can be configured using the `--extension` option:

```
$ npx squint compile --help
Usage: squint compile <files> <opts>

Options:

--elide-imports: do not include imports
--elide-exports: do not include exports
--extension: default extension for JS files
```

Let me me know if this isn't sufficient

**Comment by MTrost** [comment]
Hi hi 👋 

It seems that I missed some iterations, and everything I wished for here is already implemented.

And regarding the `#jsx` I didn't make myself clear: I meant, that files with `#jsx` in it should be ignored when changing the file extension and still compile to `.jsx` files. So exactly as it is already implemented!

Closing this, thanks for your work!
