### ISSUE TITLE
Consider adopting seq protocol + cached seqs

### ISSUE THREAD

**Issue by borkdude** [squint-cljs/squint#297]
Producing seqs that are closer to what CLJS does may lead to less surprises:

- Iterating over a seq multiple times doesn't (e.g. using `count`) cause multiple side effects
- Getting the `first` and `rest` of a seq doesn't require you to calculate the first element multiple times

A potential downside of this approach is worse performance, so this issue requires some hammock time. 

One possibility could be to only produce cached seqs when `seq` is explicitly called, but this could lead to even more surprises since a lot of core functions in CLJS produce seqs by default.

Some work has been added to [this branch](https://github.com/squint-cljs/squint/tree/iterator-seq) to enable it:

``` clojure
class IteratorSeq {
  constructor(value, iter) {
    this.value = value;
    this.rest = null;
    this.iter = iter;
  }
  [IIterable] = true;
  *[Symbol.iterator]() {
    yield this.value;
    if (this.rest == null) {
      this.rest = es6_iterator_seq(this.iter);
    }
    if (this.rest != null) {
      yield* this.rest;
    }
  }
}

export function es6_iterator_seq(iter) {
  let i = _iterator(iter);
  let v = i.next();
  if (v.done) {
    return null;
  } else {
    return new IteratorSeq(v.value, i);
  }
}
```

But performance is much slower for things like a `range` since this produces a linked list with way more garbage.
The solution CLJS takes here is to create chunked seqs for things like `range` and `map`, etc takes into account chunked seqs.

**Comment by borkdude** [comment]
@lilactown This naive approach seems to be pretty performant:

```
class MemoIter {
  constructor(iter) {
    this.rest = null;
    this.iter = iter;
    this.buf = [];
  }
  [IIterable] = true;
    *[Symbol.iterator]() {
      var ctr = 0;
      while (true) {
        let elt = this.buf[ctr];
        if (elt == undefined) {
          let val = this.iter.next();
          if (val.done) {
            break;
          }
          else {
            this.buf[ctr] = val;
            ctr++;
            yield val;
          }
        }
        else {
          ctr++;
          yield elt;
        }
      }
    }
}

export function memo_iter(iter) {
  let i = _iterator(iter);
  return new MemoIter(i);
}
```

```
$ ./node_cli.js -e "(def xs (range 1000)) (def ys (memo-iter (map identity xs))) (time (prn [(count (vec ys)) (count (vec ys))]))"
[1000,1000]
"Elapsed time: 0.962167 msecs"
```

And side effects are only caused once:

```
$ ./node_cli.js -e "(def xs (range 2)) (def ys (memo-iter (map prn xs))) (time (prn [(count (vec ys)) (count (vec ys))]))"
0
1
[2,2]
"Elapsed time: 0.712375 msecs"
```

**Comment by borkdude** [comment]
Now also made `empty?` work, which realizes only the head:

https://github.com/squint-cljs/squint/commit/f5bff577014ffb4429b6d7893cf9580cf6060915

```
$ ./node_cli.js -e "(def xs []) (def ys (memo-iter (map prn xs))) (js/console.log (empty? ys))"
true
```

**Comment by borkdude** [comment]
I think the above may be a reasonable default, and we could just document that `seq` doesn't return `nil` but always an object which you should call `empty?` on to determine if it's empty (which realizes only the first element).

**Comment by borkdude** [comment]
I guess one disadvantage of the `MemoIter` is that realized elements won't be garbage collected until you release the whole object, unlike with seqs in CLJS. But maybe we already had this problem with the current squint approach as well?

**Comment by lilactown** [comment]
it's a regression if you're using something like `(range)` which has no backing results normally.

**Comment by borkdude** [comment]
@lilactown well, we can diverge for `range` of course, which CLJS also does: it has bespoke support for it.

**Comment by lilactown** [comment]
Yeah. Typing to think, if we broke the design into two cases:

1. Sequences which are likely finite and/or backed by a concrete collection (e.g. results of `map`, `reduce`, `for` over an array)
2. Sequences which could possibly be infinite, such as `(range)` or a `(lazy-seq ,,,)`

Calling `iterable` on (1) could produce a `MemoIter`. We could also provide a utility fn to clear the cache on an object if you're memory sensitive.

Calling `iterable` on (2) could produce a `LazyIterable` like it does today. Calling `seq` or `empty?` would compute the first element and it would have no cache.

You could then have the results of each sequence operation return the appropriate type based on the input type and the operation. E.g.

```
MemoIter -> MemoIter
       (rest)

MemoIter -> MemoIter
       (map)

MemoIter -> LazyIterable
       (cycle)

LazyIterable -> LazyIterable
           (rest)

LazyIterable -> LazyIterable
           (map)

LazyIterable -> MemoIter
           (take)

MemoIter + LazyIterable -> MemoIter
                      (map)

MemoIter + LazyIterable -> LazyIterable
                      (for)
```

Typing it all out, it seems a bit delirious. But maybe worth it 🤔 Clojure does something similar with chunking. Which has been proven to be a footgun in some cases. Caching semantics seems even more important. Anyway, food for thought.

**Comment by borkdude** [comment]
I don't understand why you would want to make `lazy-seq` behave differently? You can run into situations where you realize an absurd amount of data of a lazy-seq and hang on to it in CLJS as well.

**Comment by lilactown** [comment]
I guess what I'm really thinking about is how to stop this from OOMing in Squint.

```clojure
(doseq [n ((fn fib [a b] 
             (lazy-seq (cons a (fib b (+ a b)))))
           0 1)]
  (prn n))
```

Since the iterable keeps a reference to the previous iterable, you implicitly hang on to the head even if your code seems to allow GC. This is the case for all iterables as implemented. Caching would hypothetically make this even worse, as you'd keep not only the previous iterable but also all results. If we go the lazy-immutable route fully, we could build an actual lazy cons that didn't hold on to the head maybe..

I'm probably retreading a lot of the same ground we did the last time, I can't keep it all in my head after I move away from the problem 😅 . I should probably write some of this down in a location that's easy to find in the future.

**Comment by borkdude** [comment]
Yes, we could approach this a little bit more systematically with a table that lists all options... :)

Alternative closest to current impl:

- Implement `seq` as something that takes an iterable from the `lazy`, invokes `.next()` and returns either `nil` in case `done` is false or the lazy itself...

**Comment by borkdude** [comment]
Perhaps that closest alternative is the safest bet short term. If people want caching, they can use `vec` to realize stuff I guess.

**Comment by borkdude** [comment]
Meh, that's not optimal either. Take e.g. the case when you're iterating in a loop and call `(seq ...)` on every iteration, then you would calculate each element twice.

**Comment by borkdude** [comment]
Some reading material about the reasons behind chunked seqs:

https://www.reddit.com/r/programming/comments/afyav/comment/c0headd/
https://www.infoq.com/news/2009/12/clojure-11-rc1-transients/

The main reason for chunked sequences are to avoid the overhead induced by creating a linked list for every single element.
So I think it strikes a balance between the `IteratorSeq` and `MemoIter`.

**Comment by borkdude** [comment]
Tried a combination of both approaches. After 32 elements the MemoIter continues with another MemoIter in a linked-list fashion such that there is only a 32-sized array per MemoIter:

https://github.com/squint-cljs/squint/blob/e9ec1e263132f9ffef1dcf5c6fe726ca17339ede/core.js#L1197-L1202

But an example like this triggers a stackoverflow:

```
import * as squint from 'squint-cljs/core.js';

let i = squint.memo_iter(squint.range(1000000));
let j = squint.last(i);

console.log(j);
```

**Comment by borkdude** [comment]
I have another seq branch with a `IteratorSeq` data structure (it might be similar to `MemoIter`). I changed the `seq` function to return an `IteratorSeq` which cached per 32-sized arrays.

This is the main branch:

```
./node_cli.js -e '(do (time (vec (map inc (map inc (map inc (map inc (-> (js/Array 1000000) (.fill 1)))))))) nil)'
"Elapsed time: 109.701791 msecs"
```

with everything based on iterators (fastests).

Compared to planck:

```
$ plk -e '(do (time (vec (seq (map inc (map inc (map inc (map inc (-> (js/Array 1000000) (.fill 1))))))))) nil)'
"Elapsed time: 654.772875 msecs"
```


The seq branch can't even run this example since it runs into:

```
$ ./node_cli.js -e '(do (time (vec (seq (map inc (map inc (map inc (map inc (-> (js/Array 1000000) (.fill 1))))))))) nil)'
file:///Users/borkdude/dev/squint/src/squint/core.js:515
      return lazy(function* () {
                            ^

RangeError: Maximum call stack size exceeded
```

https://github.com/squint-cljs/squint/commit/19c71f04915b127d9a755efb2d6ad3ddcafc5eba

Just writing this down as notes.
A good argument to keep the iterator based approach is performance. One thing I'm still not so happy about is that it's not easy to make `seq` return `nil` without evaluating elements twice.

**Comment by borkdude** [comment]
I thought of some other options, since I still like the current iterator approach, but to avoid pitfalls:

- Warn in `seq` when someone calls it on a non-counted (realized, non-lazy) collection (such that lazy elements are never evaluate twice)
- Warn in LazyIterable when it's used more than once (re-use before realization)

Both could be global options/vars that can be enabled for debugging.

**Comment by borkdude** [comment]
I'll stay with the iterable approach for as long as possible
