### ISSUE TITLE
squint compile --stdout

### ISSUE THREAD

**Issue by jruz** [squint-cljs/squint#318]
Hi thanks a lot this is such a joy to use.

Could it be possible to add an option to print out the compilation output instead of writing the file?

I would like to integrate this as as vite/rollup plugin

**Comment by borkdude** [comment]
Of course! Would you like to provide a PR? It's not so hard to add. Else I'll do it.

**Comment by jruz** [comment]
awesome thanks, will send you a PR tomorrow

**Comment by jruz** [comment]
I think i got confused and I should be able to accomplish the same by importing the compiler
```js
import { compileString } from 'squint-cljs/lib/compiler.js'
```
I'm a bit confused if I should be using cherry for this, same import is available in both packages but I get a different output from cherry, squint worked right away.
I'll look into the details of the difference tomorrow.

**Comment by borkdude** [comment]
cherry is similar to squint, but has a different purpose, it's closer to the real CLJS in terms of data structures. If you just want to use squint, use squint, why would you use cherry?

**Comment by borkdude** [comment]
We can discuss on Clojurians Slack if you're hanging out there, perhaps it's a quicker way to sort this out.

**Comment by jruz** [comment]
Thanks I'll close this since I solved my need with the compiler and I'll ask around in slack if I run into smth else :)

**Comment by borkdude** [comment]
@jruz Cool. Is your work public? Perhaps we can add some docs on how to use the JS interface with rollup or otherwise.
