### ISSUE TITLE
Accidental var naming with reserved keywords

### ISSUE THREAD

**Issue by jruz** [squint-cljs/squint#320]
Just ran into this were naively was defining a variable with same name as a core function, and trying to figure out why wasn't working.

Thanks a lot @borkdude for pointing it out 🙏🏼 

Maybe some error msg is possible? or we could add to the docs a warning to not create vars with names [this list](/squint-cljs/squint/blob/main/resources/squint/core.edn)?

```cljs
(def count 0)

(defn increment []
   (set! count (+ count 1)))
```

output:
```js
import * as squint_core from 'squint-cljs/core.js';
var count = 0;
var increment = (function () {
  return squint_core.count = (squint_core.count + 1);
});
```

**Comment by borkdude** [comment]
Yeah, this needs to be fixed, thanks for reporting.
