### ISSUE TITLE
Preserve comments

### ISSUE THREAD

**Issue by jruz** [squint-cljs/squint#321]
Hi could it be possible to preserve comments?

I'm writing a module and would like to use JSDoc so the end user of the compiled JS gets type definitions.

input
```cljs
;;;;
;; @type {function(number, number): number}
;;;;
(defn total [a b]
  (+ a b))
```
current output
```js
var total = (function (a, b) {
return (a + b);
})
;
```

expected output
```js
/**
 * @type {function(number, number): number}
 */
var total = (function (a, b) {
return (a + b);
})
;
```

**Comment by borkdude** [comment]
Can you try this with:

```
(js* "/** ... **/)
```
?

**Comment by jruz** [comment]
That worked thanks!
I get an extra `;` but that has no impact :)

```js
/**
 * @type {function(number, number): number}
 */;
var total = (function (a, b) {
return (a + b);
})
;
 ```

**Comment by jruz** [comment]
Actually the `;` does interfere with the type being picked up but adding an extra line break puts it into a single line and I can get it cleaned with prettier as part of the build process

```cljs
(js* "
/**
 * @type {function(number, number): number}
 */
")
(defn total [a b]
  (+ a b))
```
