### ISSUE TITLE
Make `number?` `NaN` safe

### ISSUE THREAD

**Issue by sher** [squint-cljs/squint#348]
Currently `number?` will return `true` if the value is `NaN` as it is a number.
https://github.com/squint-cljs/squint/blob/main/src/squint/core.js#L1400

Should we change the check?
```js
return typeof x == 'number' && !Number.isNaN(x);
```

Or use something more restrictive, perhaps?
```js
return Number.isFinite(x);
```

**Comment by borkdude** [comment]
I'm just following the official CLJS implementation here:

```
cljs.user=> (str (fn [x] (number? x)))
"function (x){\nreturn typeof x === 'number';\n}"
```

**Comment by borkdude** [comment]
CLJS has another predicate named `NaN?`, we should just add that
