### ISSUE TITLE
vite-react example does not work

### ISSUE THREAD

**Issue by sorumehta** [squint-cljs/squint#355]
**version**

0.3.36

**problem**

After following the steps suggested in README file of examples/vite-react, opening the server throws error "This localhost page can’t be found"

**expected behavior**

Should be able to see the cool page showing a button and the click count

**Comment by borkdude** [comment]
I added to the instructions:

```
- Create a `package.json` file
```

and

```
- Create a `public/index.html` page (see [public/index.html](public/index.html)).
```

Can you try again?

**Comment by borkdude** [comment]
This turned out to be an issue with `.gitignore` which ignored the `public` directory I had locally.
