### ISSUE TITLE
example for Threejs project

### ISSUE THREAD

**Issue by sorumehta** [squint-cljs/squint#356]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
I realise this is an oddly specific request. I want to do generative art in Clojure using ThreeJS and Squint. But since squint is very new, I can't find resources on how to use threejs library with it.

**Describe the solution you'd like**
A sample ThreeJS project in examples/ dir would be much appreciated. For reference, [here is Jack Rusher's](https://github.com/jackrusher/gespensterfelder) small generative system implemented in Clojurescript and Threejs.

**Describe alternatives you've considered**
Alternative is to use plain Javascript, but I am trying to learn Clojure here.

**Comment by borkdude** [comment]
I think Jack's project should be relatively compatible with squint, except for the applied-science.js-interop library. 
What I would do to get started is just copy the `examples/vite-react` example to `examples/threejs` and then copy Jack's index.html and `src` files.
Then run `npm install` + `npx squint watch` and `npx vite --config vite.config.js`. Then replace the applied-science.js-interop calls with native calls, or if you want to preserve the original code, rename `.cljs` to `.cljc` and use reader conditionals or the mock macros from https://github.com/nextjournal/clojure-mode/blob/main/src-squint/applied_science/js_interop.cljc.
I don't have much time today, but initial PR welcome if you want to get started.

**Comment by borkdude** [comment]
See here: https://github.com/squint-cljs/squint/tree/main/examples/threejs
It doesn't run with squint form npm, you need to build it locally. I will release a new squint version soon.

**Comment by borkdude** [comment]
Now you can run the examples/threejs demo with 0.3.38. 

cc @jackrusher

**Comment by sorumehta** [comment]
@borkdude Thanks a lot for doing this, and sorry for not being able to raise the initial PR due to lack of time.

**Comment by borkdude** [comment]
@sorumehta No worries. I discovered a few glitches that I managed to address so it was good going through this exercise.
