### ISSUE TITLE
Send nrepl server results parsable as Clojure data and support pretty printing

### ISSUE THREAD

**Issue by PEZ** [squint-cljs/squint#364]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

The v0 nrepl server is sending results back as strings containing JavaScript data. Most nrepl clients are Clojure IDEs, though, so this can break things a bit. And does so in Calva.

**Describe the solution you'd like**
I want it to use Clojure data instead. And also to support common cider-nrepl pretty print options.

**Describe alternatives you've considered**
Making Calva aware of nrepl servers sending JavaScript data, but it takes quite a lot of consideration and design which I'd like to hammock a bit.

**Additional context**

**Comment by borkdude** [comment]
Fixed
