### ISSUE TITLE
Generating markup for React Native components.

### ISSUE THREAD

**Issue by Guliy** [squint-cljs/squint#380]
**version**

"version": "0.4.56"

**problem**

There is problem with generated markup for React Native 
```
  #jsx [:View
        [:Text “Hello”]
        [:Text “World!“]]
```
translates to
```
return <View><Text>Hello</Text> <Text>World!</Text></Vew>;
```
Here we have space between <Text> tags
And RN compiler thorws error for this space:
“Unexpected text node: . A text node cannot be a child of a <View>.”
For the web its works with warning, but for app on device - crash.

**expected behavior**

Expected that there would be no extra spaces between tags

**Comment by borkdude** [comment]
Should be fixed in v0.4.58
