### ISSUE TITLE
Exporting a Class defined via defclass + async method

### ISSUE THREAD

**Issue by KAllan357** [squint-cljs/squint#446]
I was reading your blog posting `Writing a Cloudflare worker with squint and bun` and going through a similar set of steps attempting to get working example of a [Cloudflare Durable Object](https://developers.cloudflare.com/durable-objects/get-started/).

It could be my inexperience using CLJS, but I was unable to get it a "hello world" example to work without manually editing the output of `npx squint compile`. Here's Cloudflare's example:

```
export class DurableObjectExample {
  constructor(state, env) {}

  async fetch(request) {
    return new Response("Hello World");
  }
}
```

1. Exporting a class defined via `defclass` seems unsupported. Is there a way to export a class defined with `defclass`? Or an alternative method?
2. Defining a function as async via `defclass` also seemed unsupported. Is there an alternative for that?

Example CLJS:

```
(defclass DurableObjectExample 
  (field state)
  (field env)
  (constructor [this st e]
               (set! state st)
               (set! env e))

  Object
  (fetch [this request]
         (js/Response. "Hello World!")))
```

The first issue above was the primary blocker to getting the example working - when I edited the `index.js` output and add `export` to the class, it would end up working.

**Comment by borkdude** [comment]
@KAllan357 That the class isn't exported might be a bug. You can fix it for now by manually writing:

```
(js* "export DurableObjectExample")
```

at the bottom of your file.

As for the async function, does `^:async (fetch ...)` work? If not, I'll fix that as well.

**Comment by KAllan357** [comment]
@borkdude Thank you, this helps.

```
✘ [ERROR] Unexpected "DurableObjectExample"

    out/index.js:24:7:
      24 │ export DurableObjectExample;
         ╵        ~~~~~~~~~~~~~~~~~~~~
```

Adding `(js* "export { DurableObjectExample }")` fixed it.

Adding `^:async` does not seem to work:

```
  ^:async (fetch [this request]
         (js/Response. "Hello World!")))
```
did not result in async appearing in the class's function.

**Comment by borkdude** [comment]
I found another workaround for the async function:

``` clojure
(ns example (:require [squint.core :refer [defclass]]))

(defclass DurableObjectExample 
  (field state)
  (field env)
  (constructor [this st e]
               (set! state st)
               (set! env e)))

(set! DurableObjectExample.prototype -fetch
      ^:async
      (fn [this request]
        (js/console.log :this this :request request)
        (js/Response. "Hello world")))

(js* "export { DurableObjectExample }")
```

I'll fix both issues tomorrow.

**Comment by borkdude** [comment]
Both issues should be fixed in v0.4.84

**Comment by borkdude** [comment]
An async Object function can be created as follows:

```
Object
(^:async fetch [_] ...)
```

**Comment by KAllan357** [comment]
Confirmed. Thank you!
