### ISSUE TITLE
Mobile layout for the Squint playground

### ISSUE THREAD

**Issue by WilhelmBerggren** [squint-cljs/squint#447]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/squint-cljs/squint/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

## Problem
I will often click links to the Squint playground on mobile, but the current design makes it very difficult to read:
<img width="619" alt="image" src="https://github.com/squint-cljs/squint/assets/20476041/96daad2f-39bb-4182-a44a-b40b66536bd8">

## Proposed solution
The editor and sidebar should be stacked vertically when device width is under a certain value.
<img width="848" alt="image" src="https://github.com/squint-cljs/squint/assets/20476041/93014639-0a1e-4b5b-b95b-7d642c8aa163">

I am happy to open a PR for this if desired.

**Comment by borkdude** [comment]
PR welcome!

**Comment by WilhelmBerggren** [comment]
Fixed

**Comment by borkdude** [comment]
If you want, you can also make a PR for cherry. It's almost the same code. Will do it myself if I don't forget at a later point.

**Comment by WilhelmBerggren** [comment]
Oh sure, I can have a go!
