### ISSUE TITLE
Rich comment leads to eslint error

### ISSUE THREAD

**Issue by benjamin-asdf** [squint-cljs/squint#458]
**version**

"^0.6.88"

**problem**

(comment) compiles to "null;"
This is a eslint error, else would not matter.

Expected an assignment or function call and instead saw an expression.

**repro**

put a (comment) at the bottom and lint with eslint.

**expected behavior**

I am not sure. I guess you have to problem that you want it to be an expression somewhere else.
Maybe it would not emit toplevel "null;"?

**Comment by borkdude** [comment]
makes sense, will fix

**Comment by borkdude** [comment]
Released 0.6.90
