### ISSUE TITLE
Not using alias when using symbol in require

### ISSUE THREAD

**Issue by martinklepsch** [squint-cljs/squint#472]
**version**

0.6.94

**repro**

```cljs
;; squint compile repro.cljs
(require '[figma-util :as fu])
(fu/test)
```

```js
import * as squint_core from 'squint-cljs/core.js';
import * as fu from 'figma-util';
figma_util.test();    // ❌ should be `fu.test()`, right?
```

**expected behavior**

Use the correct alias provided, `fu` in this case:

```js
import * as squint_core from 'squint-cljs/core.js';
import * as fu from 'figma-util';
fu.test();
```

**Comment by borkdude** [comment]
@martinklepsch is figma-util a JS library or a CLJS file on the path?

**Comment by martinklepsch** [comment]
It's ultimately a CLJS file but does that matter for the repro? 

For context: I've been using vite/rollup with some good success to resolve/transform squint source files. I ran into this issue when I was just trying to see if I could implement support for namespace requires using a custom module resolver (sharing below just in case its interesting). 


```
import { defineConfig } from "vite";
import { compileString } from "squint-cljs";
import esbuild from "esbuild";

function namespaceResolve () {
  return {
    name: 'my-example', // this name will show up in logs and errors
    resolveId ( source ) {
      if (source === 'figma-util') {
        console.log("source:", source)
        // this signals that Rollup should not ask other plugins or check
        // the file system to find this id
        return "/path/to/figma-util.cljs";
      }
      return null; // other ids should be handled as usually
    }
  };
}

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    emptyOutDir: false
  },
  plugins: [
    namespaceResolve(),
    {
      name: "squint_compile",
      transform: function (src, id) {
        if (/\.cljs$/.test(id)) {
          console.log("squint_compile", id)
          var jsx = compileString(src);
          var js = esbuild.transformSync(jsx, { loader: "jsx" }).code;
          // TODO handle warnings from esbuild transform
          return { code: js, map: null };
        }
      },
    },
  ],
});
```

**Comment by borkdude** [comment]
> It's ultimately a CLJS file but does that matter for the repro?

Yes. Symbol namespaces are expected to be a file on the path (as described in `squint.edn`). If it can't be resolved to a file, the alias is just resolved to whatever the original name was.
I agree that the handling of the alias later on is inconsistent, but the behavior is undefined anyway in this case.
If you change the .js file manually to `fu.test();` does it work how you want it to work? Since `import * as fu from 'figma-util'` only works if `figma-util` is a JS library in `node_modules`.

**Comment by martinklepsch** [comment]
> Since `import * as fu from 'figma-util'` only works if `figma-util` is a JS library in `node_modules`.

I think it can also work by implementing a custom resolver with a tool like rollup. That resolver could look at `figma-util` and find the respective `.cljs` file. With the appropriate plugin it can also know how to transform `.cljs` into ES. 

What would be even more helpful is emitting a special marker when using symbols on the left side of require  statements, eg. adding a prefix:

```
import * as fu from 'cljs-ns:figma-util';
```

That way a Rollup plugin could have 100% confidence that cljs transform should be applied.

**Comment by borkdude** [comment]
I'm fine with changing the behavior. I'm AFK today, but can have a look tomorrow. PR also welcome.

**Comment by borkdude** [comment]
@martinklepsch To recap, I'm not sure if I get the use case for this.

In this case (the first test case from your PR):

```
$ ./node_cli.js --no-run --show -e "(require '[my.foo-bar :as foo]) (foo/some-fn)"
import * as squint_core from 'squint-cljs/core.js';
import * as foo from 'my.foo-bar';
foo.some_fn();
```

Why wouldn't you just write:

```
(require '["my.foo-bar" :as foo]) (foo/some-fn)
```

in that case?

**Comment by martinklepsch** [comment]
You mean using a string on the left side of the require? Not sure if that's what you mean but if so: I didn't realize that this would change the aliasing behavior :)

**Comment by borkdude** [comment]
yes

**Comment by martinklepsch** [comment]
Wouldn't it be weird if the left side of the require affects the right side in a subtle way like this? 

Also why would we want the old behavior? 

It's nice that this was fixable without this change to squint but still seems like a bug that deserved fixing.
