### ISSUE TITLE
`cond` in division produces wrong result

### ISSUE THREAD

**Issue by martinklepsch** [squint-cljs/squint#483]
**version**

0.6.94

**problem**

Incorrect division result when `cond` is used inside `/` form.

**repro**

```sh
yarn squint -e '(prn (/ 10 (cond true 10)))'      # -> 10
yarn squint -e '(prn (/ 10 (cond true 100) 20))'  # -> 100
```

**expected behavior**

The first invocation above should print "1"

**Comment by martinklepsch** [comment]
Totally, I noticed it works fine with `let` but yeah, felt worth opening an issue anyways 😁

**Comment by borkdude** [comment]
Yes, surely this must be fixed, thanks for the issue!
