### ISSUE TITLE
Compile to destructuring when explicit `:js` annotation is used

### ISSUE THREAD

**Issue by borkdude** [squint-cljs/squint#488]
`(defn foo [^:js {:keys [a]] a)` would compile to

```
function foo({a}) {
return a;
}
```

**Comment by martinklepsch** [comment]
This was shipped with squint-cljs 0.7.98, here's an example using it to trigger [playwright fixtures](https://playwright.dev/docs/test-fixtures#built-in-fixtures)

```clj
(require '["@playwright/test" :refer [chromium expect test]])

(def describe (.-describe test))

(def base-uri "http://localhost:3000")

(describe "playwright meets squint"
  (fn []
    (test "has title"
      (fn ^:async title-test
        [^js {:keys [page]}]
        (js/await (.goto page base-uri))
        (js/await (.toHaveTitle (expect page) #"Dynogee"))))))
```

**Comment by borkdude** [comment]
You can now also write `js-await` btw (although clj-kondo might complain, you can disable the warning with `:linters {:unresolved-symbol {:exclude [js-await]}}`. The `js/await` choice was not a good one since `js/` should only be used for global objects, and `js-...` represents special JS language built-ins

**Comment by borkdude** [comment]
Thanks for the example btw!

**Comment by borkdude** [comment]
Btw, I still have difficulty understand where "page" is coming from in that example

**Comment by martinklepsch** [comment]
> Btw, I still have difficulty understand where "page" is coming from in that example

How it works I also can't really explain but the way you can use it is described here: https://playwright.dev/docs/test-fixtures

**Comment by borkdude** [comment]
Ah gotcha, "page" is a special name that playwright will recognize.
