### ISSUE TITLE
HTML Reader wrapping everthing in quotes

### ISSUE THREAD

**Issue by brandonstubbs** [squint-cljs/squint#496]
The latest change to `html` reader seems to be wrapping every attribute in double quotes:
https://squint-cljs.github.io/squint/?src=KG5zIG1haW4KICAoOnJlcXVpcmUgWyIuL3N0eWxlLmNzcyJdCiAgICAgICAgICAgIFsiL3ZpdGUuc3ZnJGRlZmF1bHQiIDphcyB2aXRlLWxvZ29dCiAgICAgICAgICAgIFsiLi9jb3VudGVyLmNsanMiIDpyZWZlciBbc2V0dXAtY291bnRlcl1dKSkKCgooc2V0ISAoLi1pbm5lckhUTUwgKGpzL2RvY3VtZW50LnF1ZXJ5U2VsZWN0b3IgIiNhcHAiKSkKICAjaHRtbCBbOmRpdgogICAgICAgICBbOmEgezpocmVmICJodHRwczovL3ZpdGVqcy5kZXYiIDp0YXJnZXQgIl9ibGFuayJ9CiAgICAgICAgICBbOmltZyB7OnNyYyB2aXRlLWxvZ28gOmNsYXNzICJsb2dvIiA6YWx0ICJWaXRlIGxvZ28ifV1dCiAgICAgICAgIDs7IFRPRE8gc3F1aW50IGxvZ28KICAgICAgICAgWzpoMSAiSGVsbG8gVml0ZSEiXQogICAgICAgICBbOmRpdiB7OmNsYXNzICJjYXJkIn0KICAgICAgICAgIFs6YnV0dG9uIHs6aWQgImNvdW50ZXIiIDp0eXBlICJidXR0b24ifV1dCiAgICAgICAgIFs6cCB7OmNsYXNzICJyZWFkLXRoZS1kb2NzIn0KICAgICAgICAgICJDbGljayBvbiB0aGUgVml0ZSBsb2dvIHRvIGxlYXJuIG1vcmUiXV0pCgooc2V0dXAtY291bnRlciAoanMvZG9jdW1lbnQucXVlcnlTZWxlY3RvciAiI2NvdW50ZXIiKSk%3D

Also see https://github.com/squint-cljs/vite-plugin-squint/pull/8

**Comment by borkdude** [comment]
Fixed 0.7.100
