### ISSUE TITLE
Qwik QRL

### ISSUE THREAD

**Issue by brandonstubbs** [squint-cljs/squint#498]
In the Qwik Framework, they have a concept of [QRL](https://qwik.dev/docs/advanced/qrl/).

I have the following `button`:
```clojure
(ns app
  (:require ["@builder.io/qwik" :refer [component$ useSignal]]
            ["./app.css"]))

(defn -App []
  (let [count (useSignal 0)]
    #jsx [:button {:onClick$ #(set! (.-value count) (inc (.-value count)))}
          "count is " (.-value count)]))

(def App (component$ -App))
```

This is the output
```jsx
<button onClick$={(function () {return count1.value = (count1.value + 1);})}>count is {count1.value}</button>
```

This would be the ideal output:
```jsx
<button onClick$={() => { return count1.value = (count1.value + 1);}}>count is {count1.value}</button>
```

Qwiks [$](https://qwik.dev/docs/advanced/dollar/) optimiser needs serializable values.

**Comment by borkdude** [comment]
Can you be more specific on what is the difference in output? Is that only the arrow function vs `function` function?

**Comment by brandonstubbs** [comment]
Yeah seems it works better with the arrow function [clojure](https://qwik.dev/docs/advanced/dollar/#closures) output

**Comment by borkdude** [comment]
I don't see how `function` is less serialisable than `() => {}`

**Comment by brandonstubbs** [comment]
This is the error output:
<img width="1316" alt="image" src="https://github.com/squint-cljs/squint/assets/3731434/fce20db0-c267-4bc9-8ede-c4553a3f70da">

Maybe more an issue their side

**Comment by borkdude** [comment]
So I guess we could use a syntax in squint to produce "arrow" functions instead, e.g. `(fn ^:whatever [])`, I'm not sure. Any ideas?
Also, can you try out if changing that `function` to `() => {}` in the output really fixes the issue?

**Comment by brandonstubbs** [comment]
Yeah changing the output fixes the issue.

Is there a reason the `function` is preferred over arrow functions? I wonder if maybe this would be better to be a squint compiler flag to emit all functions as arrow functions? Or at least functions in JSX as arrow functions.

**Comment by borkdude** [comment]
I some cases `function` is necessary since `()` doesn't support `this`

**Comment by brandonstubbs** [comment]
I think let's park this for now. I am not familiar with the framework. I was just getting the vite templates to work. I will open an issue with them first to see why the `function` way doesn't work, as  `(def App (component$ -App))` this part is also a `$` optimisation and seems to work.

**Comment by martinklepsch** [comment]
Can `function` be serialized less well than arrow fns? This seems like an odd requirement on Qwiks side. 

Could be useful to provide some low level syntax helpers in squint to emit the respective syntax, maybe?

**Comment by brandonstubbs** [comment]
So it seems you can wrap the function in their `$` function:

```clojure
(ns app
  (:require ["@builder.io/qwik" :refer [component$ useSignal $]]
            ["./app.css"]))

(defn -App []
  (let [count (useSignal 0)]
    #jsx [:button {:onClick$ ($ #(set! (.-value count) (inc count)))}
          "count is " (.-value count)]))

(def App (component$ -App))
```

This compiles to:
```jsx
<button onClick$={$((function () { return count1.value = (count1 + 1);}))}>count is {count1.value}</button>
```

If the extra param wasn't added around the function this would work. It should look like this instead:
```jsx
<button onClick$={$(function () { return count1.value = (count1 + 1);})}>count is {count1.value}</button>
```

**Comment by brandonstubbs** [comment]
Simple example of the extra paren from `squint.compiler/compile-string`:

```clojure
(compile-string  "(defn test [] #jsx [:button {:onClick #(+ 1 1)}])")
; import * as squint_core from 'squint-cljs/core.js';
; var test = function () {
; return <button onClick={(function () {
; return (1) + (1)
; })}></button>
; };
;
; export { test }
;
```

**Comment by borkdude** [comment]
>  IMHO (fn ...) should emit arrow functions by default 

This isn't done because of compatibility with existing CLJS code

**Comment by martinklepsch** [comment]
I added an issue for just this arrow function syntax stuff https://github.com/squint-cljs/squint/issues/499

**Comment by martinklepsch** [comment]
I created an issue but also realized that maybe we should just rename this one, then all context is in one place.

**Comment by borkdude** [comment]
#499 is fixed, I think this should work now
