### ISSUE TITLE
`compileString` adds extra paren jsx

### ISSUE THREAD

**Issue by brandonstubbs** [squint-cljs/squint#501]
**version**
0.7.100

**problem**
`compileString` adds an extra paren in jsx

**repro**
```clojure
(compile-string  "#jsx [:button {:onClick #(+ 1 1)}]")
; import * as squint_core from 'squint-cljs/core.js';
; <button onClick={(function () {
; return (1) + (1)
; })}></button>;
;
```

**expected behavior**
The `onClick` function or the value `1` should not be wrapped in an extra paren
```clojure
(compile-string  "#jsx [:button {:onClick #(+ 1 1)}]")
; import * as squint_core from 'squint-cljs/core.js';
; <button onClick={function () {
; return 1 + 1
; }}></button>;
;
```

**Comment by brandonstubbs** [comment]
This relates to this comment https://github.com/squint-cljs/squint/issues/498#issuecomment-2028305263

**Comment by borkdude** [comment]
This isn't related to JSX:

```
 ./node_cli.js --show -e '(def a #js {:a #(do 1) :b (+ 1 2 3) :c 3})'
import * as squint_core from 'squint-cljs/core.js';
var a = ({ "a": (function () {
return 1
}), "b": (1) + (2) + (3), "c": 3 });
```

I don't consider this a bug. If tools have problems with wrapping parens, I consider it their bug. The output of squint is very similar to what CLJS does.

**Comment by borkdude** [comment]
I think the parens were mostly added for when you use functions as expressions on the top level:

```
> (function () {})
[Function (anonymous)]
> function () {}
function () {}
^^^^^^^^

Uncaught SyntaxError: Function statements require a function name
```

**Comment by borkdude** [comment]
Also in cases like this:

```
$ ./node_cli.js --show -e '(#(do %) 1)'
import * as squint_core from 'squint-cljs/core.js';
(function (_PERCENT_1) {
return _PERCENT_1
})(1);
```

**Comment by borkdude** [comment]
I think if we would just fix the "arrow" function issue, then we wouldn't have to do anything about this, so let's focus on that one.
