### ISSUE TITLE
Support keywords as functions in higher order functions

### ISSUE THREAD

**Issue by benjamin-asdf** [squint-cljs/squint#507]
(juxt :id identity)

this becomes squint_core.juxt("id", squint_core.identity)

Could it support keyword functions?

**Comment by benjamin-asdf** [comment]
Also maps and so forth as functions? I guess that implies passing around some `callable` object.

**Comment by borkdude** [comment]
I looked into it and juxt already supports "keyword functions".
In squint keywords simply translate to strings. In squint's version of juxt, strings are interpreted as lookup functions:

```
$ ./node_cli.js --show -e '(js/console.log ((juxt :foo :bar) {:foo 1 :bar 2}))'
import * as squint_core from 'squint-cljs/core.js';
console.log(squint_core.juxt("foo", "bar")(({ "foo": 1, "bar": 2 })));

[ 1, 2 ]
```
