### ISSUE TITLE
`squint/core` Shuffle function suggestions

### ISSUE THREAD

**Issue by kigiri** [squint-cljs/squint#513]
https://github.com/squint-cljs/squint/blob/6d6e3fc5ca3dcd129aa7eea9fcdbb7e4167860f7/src/squint/core.js#L1851-L1855

This is not a good way to shuffle, distribution is biased, and it's not efficient.

```js
function shuffle(coll) {
  const result = [...coll]
  let left = coll.length
  while (left) {
    const i = Math.floor(Math.random() * left--)
    const tmp = result[left]
    result[left] = result[i]
    result[i] = tmp
  }

  return result
}
```

Here an example of the distribution in chrome:
![image](https://github.com/squint-cljs/squint/assets/231748/b5ba511b-770c-411a-903c-b7c9a1a43af5)

You can read more about why this isn't a recommanded method here:
[https://stackoverflow.com/questions/962802/is-it-correct-to-use-javascript-array-sort-method-for-shuffling](https://stackoverflow.com/questions/962802/is-it-correct-to-use-javascript-array-sort-method-for-shuffling)

And here, clicking on the solution for straitforward examples: [https://javascript.info/task/shuffle](https://javascript.info/task/shuffle)

**Comment by borkdude** [comment]
Thanks!

**Comment by borkdude** [comment]
The source code you list after the squint link, is that a recommendation of how to do it, or not?
It seems fairly close to how goog.array is doing it: https://github.com/google/closure-library/blob/master/closure/goog/array/array.js#L1741
If so, PR welcome
