### ISSUE TITLE
`squint/core` Prefer slice over pop

### ISSUE THREAD

**Issue by kigiri** [squint-cljs/squint#514]
https://github.com/squint-cljs/squint/blob/6d6e3fc5ca3dcd129aa7eea9fcdbb7e4167860f7/src/squint/core.js#L2666C1-L2674C2

Could be done like so:

```js
export function pop(vec) {
  if (array_QMARK_(vec)) {
    return vec.slice(0, -1);
  } else {
    return rest(vec);
  }
}
```

Also, what is your opinion about ternaries ? I was wondering if it would make any difference in the size of the final bundle:
```js
export function pop(vec) {
  return array_QMARK_(vec) ? vec.slice(0, -1) : rest(vec)
}

**Comment by borkdude** [comment]
You haven't explained why one solution should be preferred over another. Could you explain this? We have issue templates for a reason: https://github.com/squint-cljs/squint/tree/main/.github/ISSUE_TEMPLATE
If you choose not to fill out the issue templates, this will mean I have to spend more time getting the issue clear.

As for ternaries: I find that style harder to read and write. I think tools like esbuild might still optimize them:

```
$ echo 'function foo(x) { if (x) return 3; else return 4 }' | npx esbuild --minify
function foo(e){return e?3:4}
```

**Comment by borkdude** [comment]
FWIW, I have ran some benchmarks and it's not clear why one should be preferred over the other in terms of performance:

```
cljs.user=> (def f1 (js/eval "(x) => { const y = [...x]; y.pop(); return y }")
)
#'cljs.user/f1
cljs.user=> (time (dotimes [i 10000000] (f1 #js [1 2 3 4])))
"Elapsed time: 250.718358 msecs"
nil
cljs.user=> (time (dotimes [i 100000000] (f1 #js [1 2 3 4])))
"Elapsed time: 2527.854460 msecs"
nil
cljs.user=> (def f2 (js/eval "(x) => { const y = x.slice(0,-1); return y }"))
#'cljs.user/f2
cljs.user=> (f2 #js [1 2 3 4])
#js [1 2 3]
cljs.user=> (time (dotimes [i 100000000] (f2 #js [1 2 3 4])))
"Elapsed time: 2696.102957 msecs"
nil
cljs.user=> (f2 #js [1 2 3 4])
#js [1 2 3]
cljs.user=> (time (dotimes [i 100000000] (f2 #js [1 2 3 4])))
"Elapsed time: 2795.635011 msecs"
nil
cljs.user=> (time (dotimes [i 100000000] (f1 #js [1 2 3 4])))
"Elapsed time: 2442.380751 msecs"
nil
cljs.user=> (time (dotimes [i 1000000
```

**Comment by kigiri** [comment]
@borkdude Sorry for not seeing your reply earlier and missing the reply, it was more for simplicity than performances since you could return the value directly.

I didn't know about the minify, great to see, but if you have to use an intermediate variables you won't be able to benefit from it.

Other than that it's perfectly fine to keep the pop if you find the clarity of the implementation better, I was not trying to play the micro benchmark JS game.

And thank you for the link to the issue template, I've missed it somehow !

**Comment by borkdude** [comment]
@kigiri No problem, I appreciate your feedback!
