### ISSUE TITLE
cljs is not defined when using `case`

### ISSUE THREAD

**Issue by benjamin-asdf** [squint-cljs/squint#515]
**version**
0.6.89

**problem**

Example code:

```
(ns foo)

(defn Foo [a]
  (case (:foo a)
    'b))

```

output:

```
import * as squint_core from 'squint-cljs/core.js';
;
var Foo = function (a) {
let G__51451 = squint_core.get(a, "foo");
switch (G__51451) {default:
return cljs.core.symbol("b")}
};

export { Foo }

```

-> ReferenceError: cljs is not defined

**Comment by borkdude** [comment]
tl;dr: the issue isn't with case or cond, but with using a symbol `'b`. squint (as of today) doesn't have symbols. just use a keyword or a string.

**Comment by benjamin-asdf** [comment]
Additionally. In my second foo example there was an error, using {} instead of (). Then I got a react error "using object as child".
