### ISSUE TITLE
class definitions not showing in repl

### ISSUE THREAD

**Issue by tecumsehcommunications** [squint-cljs/squint#517]
**version**

0.7.105

**problem**

If you just take verbatim the example for defclass given on this website. It will not work as for some reason the classes, when defined, do not return a handle--at least to the squint repl.  The work-around I am using is to preface the declaration  with an explicit definition:

BEFORE: (doesn't work - Reference Error: class-1 is not defined)

(defclass class-1
  (field -x)
  (field -y :dude) ;; default
  (constructor [this x] (set! -x x))

  Object
  (get-name-separator [_] (str "-" -x)))

(defclass Class2
  (extends class-1)
  (field -y 1)
  (constructor [_ x y]
               (super (+ x y -y)))

  Object
  (dude [_]
        (str -y (super.get-name-separator)))
  (^:async fetch [_]
    (js/fetch "https://clojure.org"))

  (toString [this] (str "<<<<" (.dude this) ">>>>") ))

(def c (new Class2 1 2))

AFTER: (working)

**(def class-a** (defclass class-1
  (field -x)
  (field -y :dude) ;; default
  (constructor [this x] (set! -x x))

  Object
  (get-name-separator [_] (str "-" -x)))

**(def class-b** (defclass Class2
  (extends class-1)
  (field -y 1)
  (constructor [_ x y]
               (super (+ x y -y))))

  Object
  (dude [_]
        (str -y (super.get-name-separator)))
  (^:async fetch [_]
    (js/fetch "https://clojure.org"))

  (toString [this] (str "<<<<" (.dude this) ">>>>") ))

(def c (new **Class-b** 1 2))

-------------------------------------------------------
I hope this helps.  This is a magnificent language.

**Comment by borkdude** [comment]
Ah yes, this is definitely a REPL bug regarding `defclass`. Thanks, I'll have a look at fixing this soon!

**Comment by borkdude** [comment]
Fixed and released v0.7.106

**Comment by tecumsehcommunications** [comment]
I'm not seeing the change on 0.7
106.  Same test and error as before.

Prefacing the class definitions with variable declarations does allow them
to be declared as before, but when I try to instantiate the example, I now
get: Cannot access 'self__' before initialization...

**Comment by borkdude** [comment]
Can you please make a step by step repro, as I'm not sure what is not working for you.

Like:

1. command line invocation to start a REPL
2. expression entered into REPL
3. next expression: fails

**Comment by borkdude** [comment]
FWIW, it does work in the squint playground now, whereas before it didn't.

**Comment by borkdude** [comment]
I can reproduce it in a command line REPL like so:

```
$ ./node_cli.js repl
user=> (defclass Foo (constructor [x]) Object (toString [_] "yo"))
[class Foo]
user=> (Foo.)
ReferenceError: Foo is not defined
```

Is this also what you are using, or nREPL?

**Comment by borkdude** [comment]
Found the problem, will publish 0.7.108 in a bit

**Comment by borkdude** [comment]
Published

**Comment by tecumsehcommunications** [comment]
This is a screen log of what I am seeing.


***@***.***:~/lib/squint/playground$ npm list
playground@ /home/ubuntu/lib/squint/playground
├── @***@***.***
├── @***@***.***
├── @***@***.***
├── @***@***.***
├── @***@***.***
├── @***@***.***
├── @***@***.***
├── @***@***.***
├── @***@***.***
├── @***@***.***
├── @***@***.***
├── @***@***.***
├── @***@***.***
├── ***@***.***
├── ***@***.***
├── ***@***.***
├── ***@***.***
├── ***@***.***
├── ***@***.******@***.*** -> ./..
└── ***@***.***

<< Here I just copy and past from the example given >>

***@***.***:~/lib/squint/playground$ squint repl
user=> (defclass class-1
  (field -x)
  (field -y :dude) ;; default
  (constructor [this x] (set! -x x))

  Object
  (get-name-separator [_] (str "-" -x)))

<< echoed back >>

(defclass class-1
  (field -x)
  (field -y :dude) ;; default
  (constructor [this x] (set! -x x))

  Object
  (get-name-separator [_] (str "-" -x)))
[class class_1]

<< O.K. so far >>

user=> (defclass Class2
  (extends class-1)
  (field -y 1)
  (constructor [_ x y]
               (super (+ x y -y)))

  Object
  (dude [_]
        (str -y (super.get-name-separator)))
  (^:async fetch [_]
    (js/fetch "https://clojure.org"))

  (toString [this] (str "<<<<" (.dude this) ">>>>") ))

<< echoed back >>

(defclass Class2
  (extends class-1)
  (field -y 1)
  (constructor [_ x y]
               (super (+ x y -y)))

  Object
  (dude [_]
        (str -y (super.get-name-separator)))
  (^:async fetch [_]
    (js/fetch "https://clojure.org"))

  (toString [this] (str "<<<<" (.dude this) ">>>>") ))

ReferenceError: class_1 is not defined
    at eval (eval at Tha
(file:///home/ubuntu/.nvm/versions/node/v22.0.0/lib/node_modules/squint-cljs/lib/cli.js:29:46),
<anonymous>:4:22)
    at process.processTicksAndRejections
(node:internal/process/task_queues:95:5)
user=>

<< now wrap the class definition with variable declaration >>

user=> (def class1 (defclass class-1
  (field -x)
  (field -y :dude) ;; default
  (constructor [this x] (set! -x x))

  Object
  (get-name-separator [_] (str "-" -x))))

<< echo >>

(def class1 (defclass class-1
  (field -x)
  (field -y :dude) ;; default
  (constructor [this x] (set! -x x))

  Object
  (get-name-separator [_] (str "-" -x))))
undefined

<< so far so good >>

user=> ( def class2 (defclass Class2
  (extends class1)  <== changed to reflect new definition
  (field -y 1)
  (constructor [_ x y]
               (super (+ x y -y)))

  Object
  (dude [_]
        (str -y (super.get-name-separator)))
  (^:async fetch [_]
    (js/fetch "https://clojure.org"))

  (toString [this] (str "<<<<" (.dude this) ">>>>") )))

<< echo >>

( def class2 (defclass Class2
  (extends class1)
  (field -y 1)
  (constructor [_ x y]
               (super (+ x y -y)))

  Object
  (dude [_]
        (str -y (super.get-name-separator)))
  (^:async fetch [_]
    (js/fetch "https://clojure.org"))

  (toString [this] (str "<<<<" (.dude this) ">>>>") )))
undefined
user=>

<< doing better, but when I try to instantiate>>

user=> (def c (new class2 1 2))
(def c (new class2 1 2))
ReferenceError: Cannot access 'self__' before initialization
    at new Class2 (eval at Tha
(file:///home/ubuntu/.nvm/versions/node/v22.0.0/lib/node_modules/squint-cljs/lib/cli.js:29:46),
<anonymous>:6:20)
    at eval (eval at Tha
(file:///home/ubuntu/.nvm/versions/node/v22.0.0/lib/node_modules/squint-cljs/lib/cli.js:29:46),
<anonymous>:4:21)
    at process.processTicksAndRejections
(node:internal/process/task_queues:95:5)
user=>

**Comment by borkdude** [comment]
Have you tested with 0.7.108?

**Comment by tecumsehcommunications** [comment]
I only see 0.7.107 in the repository.

===================================================
 npm view squint-cljs

***@***.*** | Proprietary | deps: 1 | versions: 117
Squint is a light-weight dialect of ClojureScript with a compiler and
standard library.

bin: squint

dist
.tarball: https://registry.npmjs.org/squint-cljs/-/squint-cljs-0.7.107.tgz
.shasum: c619dc9ce7ad2ea5de1facfe7bfa557ab4b95462
.integrity:
sha512-FVMiDmh0wyERjDd2Oa+y7Uj8uMl5kKkwTQSskponxwozqu5Wdcc3rmbmv05GebBCo4o6LkfI20KabTFYeuTa3Q==
.unpackedSize: 1.4 MB

dependencies:
chokidar: ^3.5.3

maintainers:
- borkdude ***@***.***>

dist-tags:
latest: 0.7.107

published 3 hours ago by borkdude ***@***.***>

**Comment by tecumsehcommunications** [comment]
That what I'm running on.

**Comment by borkdude** [comment]
Got it, so it fails with `(extends class-1)` in the REPL
