### ISSUE TITLE
`nil` keys in map

### ISSUE THREAD

**Issue by brandonstubbs** [squint-cljs/squint#518]
**version**

`v0.7.105`

**problem**

The value `"null"` and `nil` conflict in a map

**repro**

```sh
npx squint-cljs -e '(prn {nil 10 "null" 20})'
# => {"null":20}
```

**expected behavior**

`nil` and `"null"` should be in the map

**Comment by borkdude** [comment]
I don't think this is a correct assumption since JS objects only support string keys

**Comment by borkdude** [comment]
Here is a counter-example from CLJS:

```
cljs.user=> (js-obj nil 1 "null" 2)
#js {:null 1}
```

**Comment by brandonstubbs** [comment]
Ok understood. This is another difference from squint compared to Clojurescript/Cherry.

Other keys that will not work:
- functions
- floats
- maps

As squint is using Objects vs Maps this is a good reference of differences
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#objects_vs._maps
![image](https://github.com/squint-cljs/squint/assets/3731434/7adef117-87f2-4056-8171-560210fd97b8)

For anyone coming across this issue in the future, I used an ES6 map, [see playground example](https://squint-cljs.github.io/squint/?src=KGRlZm4gZiBbXSAxKQooZGVmIG0gezphIDF9KQoKKGRlZiB4IChuZXcgTWFwIFtbbmlsIDEwXQogICAgICAgICAgICAgICAgIFsibnVsbCIgMjBdCiAgICAgICAgICAgICAgICAgW2YgMV0KICAgICAgICAgICAgICAgICBbMS41IDUuMV0KICAgICAgICAgICAgICAgICBbbSB7OmIgMn1dXSkpCgpbKGdldCB4IG5pbCkKIChnZXQgeCAibnVsbCIpCiAoZ2V0IHggZikKIChnZXQgeCAxLjUpCiAoZ2V0IHggbSld)
