### ISSUE TITLE
zipmaps are disordered

### ISSUE THREAD

**Issue by tecumsehcommunications** [squint-cljs/squint#520]
**version**

squint-cljs@0.7.105

**problem**

Zipmap does not preserve original ordering of the elements. For example:

   (zipmap [ :a :b :c :d :e :f :g :h :i :j :k :l :m] [1 2 3 4 5 6 7 8 9 10 11 12 14])

Produces:
   
   {:m 14, :e 5, :l 12, :k 11, :g 7, :c 3, :j 10, :h 8, :b 2, :d 4, :f 6, :i 9, :a 1}

**Comment by borkdude** [comment]
I can't reproduce this in the playground: 

https://squint-cljs.github.io/squint/?src=KHppcG1hcCBbOmEgOmIgOmMgOmQgOmUgOmYgOmcgOmggOmkgOmogOmsgOmwgOm1dIFsxIDIgMyA0IDUgNiA3IDggOSAxMCAxMSAxMiAxNF0p

It may just be an effect of the printing. In what way are you seeing the above result, in REPL/nREPL? Then it may be an effect of CLJS converting the JS map into a CLJS map, which are unordered, but this is then just an artifact of printing. 

Try `(keys ...)` and see what it returns

**Comment by tecumsehcommunications** [comment]
I didnt think about that.

This is happening in the scittle repl with an emacs/monroe client.  I can
confirm that it works as it should in the squint-cljs repl.

Thanks for pointing that out.  I'll take down the bug report.

**Comment by tecumsehcommunications** [comment]
Answered
