### ISSUE TITLE
How to emit try catch? 

### ISSUE THREAD

**Issue by benjamin-asdf** [squint-cljs/squint#525]
**version**

0.6.89

**problem**

I don't get how to make "catch" emit correct jsx syntax: 

```
(try (/ 1 0)
     (catch [e] "foo"))
```

```
  Expected identifier but found "\"foo\""
  16 |  try{
  17 |  (1 / 0)}
  18 |  catch("foo"){
     |        ^
  19 |  null}
  20 |  ;
```

**Comment by borkdude** [comment]
0.6.89 is a pretty old version, can you first please upgrade?
And you mention JSX? Can you make a full repro using JSX then and not just a snippet?
Preferably, make a repro using the playground by hitting the share button:

https://squint-cljs.github.io/squint/

**Comment by borkdude** [comment]
The correct syntax for try/catch it the following:

```
#html [:p (try (/ 1 0)
            (catch :default e "foo"))]
```

You have used `[e]` instead of a classname of `:default` as a catch-call followed by an identifier.

**Comment by benjamin-asdf** [comment]
Thanks that's good to know
