### ISSUE TITLE
could squint be used as a clojurescript compiler to javascript, output of which works with Scittle?

### ISSUE THREAD

**Issue by kangaroolab** [squint-cljs/squint#532]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
Scittle is a very nice and convenient runtime to run clojure code in browser. However, sometime there is need to use a 3rd party clojurescript. One option is to grab the source code of 3rd party clojurescript and eval it by Scittle, which works. But it could be another option if Squint can compile 3rd party clojurescript to javascript that can be compliant with Scittle (similar to pprint), or Sci or Scittle can output javascript itself.

**Describe the solution you'd like**
As a developer, I can use Squint to compile clojurescript to javascript that can run with Scittle in browser (meaning it can be recognized as a ns with Scittle and I can require it)

**Describe alternatives you've considered**
Always use Scittle to eval 3rd party clojurescript code

**Additional context**
N/A

**Comment by borkdude** [comment]
I don't think this will work since squint produces normal JS data structures and namespaces behave differently in Scittle than in squint. Squint isn't designed to work together with scittle to be a full replacement for the CLJS compiler. If scittle is too limiting, then just use the normal CLJS compiler e.g. with Shadow or create a scittle plugin like this:
https://github.com/babashka/scittle/tree/main/plugins/demo

**Comment by kangaroolab** [comment]
Thanks...

If Squint is meant for sth different, with Scittle, could it possible to expose its underlying parse/compile function so Scittle can be used to produce javascript file. E.g. I create a codegraph that works with Scittle in the browser by using script-tag. But it will require a in-memory compile/eval every time when the page is loaded. Would be helpful if I could compile it by Scittle to produce corresponding javascript file so I can just load the javascript (without the in-memory compile/eval) every time. I looked at the plugin examples, which seem requiring config for each. I thought it is already handy that Scittle can read/compile clojurescript on the fly so why not just enable it with an option to produce javascript?

**Comment by borkdude** [comment]
Note that scittle does not compile, it uses an interpreter called SCI.

You can already use squint to compile JavaScript on the fly, it has a JS API.
