### ISSUE TITLE
confused whether the #html behaviour is a feature or a bug. explained in detail.

### ISSUE THREAD

**Issue by dionysus98** [squint-cljs/squint#555]
## version
`"squint-cljs": "0.8.114"`
`"express": "4.21.0"`

## problem
The compiled code of #html reader tag returns a `Html` class with `{"s" : "<whatever html string>" }`.
While using the #html reader tag in `express` for sending a response:
`res.send #html [:div "oi"]` this converts to `{"s" : "<div>oi</div>"}`. 
Hence a `json` response is always being sent.

- `note`: following the `examples/express` from the `repo`.

what I'd like to know is that, if this a feature, 
that the "s" key should extracted or  the `str` function to be called by the user on each #html defs, 
or is it a bug? 

I apologise if this is the expected behaviour.

Thanks.

**Comment by borkdude** [comment]
Hey @dionysus98, you're supposed to call `(str #html ...)` on the result to serialize it as a string. This is by design to avoid double encoding of nested HTMLs.

**Comment by borkdude** [comment]
I guess we could document this better.

**Comment by dionysus98** [comment]
Ah that does make sense.
Thanks, @borkdude
