### ISSUE TITLE
using '-main' as 'export default'

### ISSUE THREAD

**Issue by 0b1kn00b** [squint-cljs/squint#570]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

Quite often with config files an `export default function....` is required, and I can't see a mechanism.

**Describe the solution you'd like**
If `-main` is defined, map it to the default export of the js file.

**Describe alternatives you've considered**
I'm hand coding access in the target source directory

**Additional context**

11ty is heavy on the config and I'd like to compose it from squint.

**Comment by 0b1kn00b** [comment]
Found typical way [here](https://github.com/squint-cljs/squint/blob/c74229f1d8521cfbc1e5739f91d3b8e7c9929547/examples/expo-react-native/src/App.cljs#L14)

```clojure
(def default  main)
```

**Comment by borkdude** [comment]
Yes, that's how it's done: `(def default)`.
