### ISSUE TITLE
Add support of `await` to `for` macro and AsyncGenerator

### ISSUE THREAD

**Issue by darkleaf** [squint-cljs/squint#594]
In js I could write like this:

```js
  async function exec(x) {
    return Promise.resolve(x)
  }

  async function* gen() {
    // yield await exec(1) // works too
    yield exec(1)
    yield exec(2)
  }

  for await (const i of gen()) {
    console.log(i)
  }
```

This code is not worked:
```clojure
(defn exec [x]
  (js/Promise.resolve x))

(defn ^:async ^:gen gen []
  (js-yield (exec 1))
  (js-yield (exec 2))
  nil)

(for ^:async [i (gen)] ;; ^:async is not supported
  (prn i))
```

+ [demo](https://squint-cljs.github.io/squint/?repl=true&src=KGRlZm4gZXhlYyBbeF0KICAoanMvUHJvbWlzZS5yZXNvbHZlIHgpKQoKKGRlZm4gXjphc3luYyBeOmdlbiBnZW4gW10KICAoanMteWllbGQgKGV4ZWMgMSkpCiAgKGpzLXlpZWxkIChleGVjIDIpKQogIG5pbCkKCihmb3IgXjphc3luYyBbaSAoZ2VuKV0gOzsgXjphc3luYyBpcyBub3Qgc3VwcG9ydGVkCiAgKHBybiBpKSk%3D)
+ [`for-await...of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of)
+ [AsyncGenerator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncGenerator)
+ [Possible workaround](https://squint-cljs.github.io/squint/?repl=true&src=KGRlZm4gZXhlYyBbeF0KICAoanMvUHJvbWlzZS5yZXNvbHZlIHgpKQoKKGRlZm4gXjpnZW4gbXlnZW4gW10KICAoanMteWllbGQgKGV4ZWMgMSkpCiAgKGpzLXlpZWxkIChleGVjIDIpKQogIG5pbCkKCihkZWZuIHJlc29sdmUgW10KICAoZm9yIFtwIChteWdlbildCiAgICBwKSkKCihqcy1hd2FpdCAoanMvUHJvbWlzZS5hbGwgKGpzLWF3YWl0IChyZXNvbHZlKSkpKQ%3D%3D)
+ [Slack message](https://clojurians.slack.com/archives/C03U8L2NXNC/p1733905263677949)

**Comment by borkdude** [comment]
I thought about this some more but I don't think this feature makes much sense for squint.

```
for await (const i of ...)
```

is equivalent to

```
for (const i of ...)
  const j = await i
```

So in squint you could just [this](https://squint-cljs.github.io/squint/?repl=true&src=KGRlZm4gZXhlYyBbeF0KICAoanMvUHJvbWlzZS5yZXNvbHZlIHgpKQoKKGRlZm4gXjpnZW4gZ2VuIFtdCiAgKGpzLXlpZWxkIChleGVjIDEpKQogIChqcy15aWVsZCAoZXhlYyAyKSkKICBuaWwpCgooZGVmbiBeOmFzeW5jIGZvbyBbXQogIChkb3NlcSBbaSAoZ2VuKV0gOzsgXjphc3luYyBpcyBub3Qgc3VwcG9ydGVkCiAgICAoanMvY29uc29sZS5sb2cgKGpzLWF3YWl0IGkpKSkpCgooZm9vKQ%3D%3D)

Introducing special syntax for `for await` isn't worth it imo.
