### ISSUE TITLE
Can't compile nested generator function

### ISSUE THREAD

**Issue by darkleaf** [squint-cljs/squint#595]
This code does not compile:
```clojure
(defn foo [a b c]
  (fn ^:gen []
    (js-yield a)
    (js-yield b)
    (js-yield c)
    nil))
```

[Demo](https://squint-cljs.github.io/squint/?src=KGRlZm4gZm9vIFthIGIgY10KICAoZm4gXjpnZW4gW10KICAgIChqcy15aWVsZCBhKQogICAgKGpzLXlpZWxkIGIpCiAgICAoanMteWllbGQgYykKICAgIG5pbCkp)

```
SyntaxError: Unexpected strict mode reserved word
```

I want to write something like this:
```js
function foo(a, b, c) {
  return function*() {
    yield a;
    yield b;
    yield c;
  }
}

for (const i of foo(1, 2, 3)()) {
  // NOTE:         ---------^^
  console.log(i);
}
```

I think it is because nested function complied as regular function:

```clojure
(defn foo [a b c]
  (fn ^:gen []
    nil))
```

```js
var foo = function (a, b, c) {
  return function () {
// correct version: return function* () {
    return null;
  };
};
```

**Comment by borkdude** [comment]
The `^:gen` annotation should go on the `fn` symbol:

```
(defn foo [a b c]
  (^:gen fn []
    (js-yield a)
    (js-yield b)
    (js-yield c)
    nil))
```

I see that this is wrong in the docs, I'll improve it.

**Comment by borkdude** [comment]
done

**Comment by darkleaf** [comment]
thanks!

https://squint-cljs.github.io/squint/?src=KGRlZm4gZm9vIFthIGIgY10KICAoXjpnZW4gZm4gW10KICAgIChqcy15aWVsZCBhKQogICAgKGpzLXlpZWxkIGIpCiAgICAoanMteWllbGQgYykKICAgbmlsKSkKCihkb3NlcSBbaSAoKGZvbyAxIDIgMykpXQogIChwcm4gaSkp
