### ISSUE TITLE
Unary division does not produce reciprocal

### ISSUE THREAD

**Issue by exupero** [squint-cljs/squint#596]
**version**

0.8.129

**problem**

Unary division with a single argument emits its argument instead of the reciprocal of its argument, as Clojure does.

**repro**

`(/ 2)` produces the code:

```javascript
import * as squint_core from 'squint-cljs/core.js';
(2);
```

**expected behavior**

In Clojure, `(float (/ 2))` produces `0.5`.

**Comment by borkdude** [comment]
Thanks, will fix
